ScaffoldDotNet7/Controllers/WatchListController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ScaffoldDotNet7.Constants;
using ScaffoldDotNet7.Data;
using ScaffoldDotNet7.Models;

namespace ScaffoldDotNet7.Controllers
{
    public class WatchListController : Controller
    {
        private readonly ApplicationDbContext movieDbContext;

        public WatchListController(ApplicationDbContext movieDbContext)
        {
            this.movieDbContext = movieDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var movies = await movieDbContext.Movies.ToListAsync();
            return View(movies);
        }

        [Authorize(Roles = "Admin")]

        [HttpGet]
        public IActionResult Add()
        {
            return View();

        }
        [HttpPost]
        public async Task<IActionResult> Add(AddMovieViewModel addMovieViewModel)
        {
            var movie = new Movie()
            {
                Id = Guid.NewGuid(),
                Name = addMovieViewModel.Name,
                Year = addMovieViewModel.Year,
                Genre = addMovieViewModel.Genre
            };

            await movieDbContext.Movies.AddAsync(movie);
            await movieDbContext.SaveChangesAsync();
            return RedirectToAction("Add");
        }


        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {
            // id = What User Want to Update
            //Id = What We Send To DB
            var movie = await movieDbContext.Movies.FirstOrDefaultAsync(x => x.Id == id);

            if (movie != null)

            {
                //We Want to Use From UpdateModel a TypeConversion needed.
                var viewModel = new UpdateMovieViewModel()
                {
                    Id = movie.Id,
                    Name = movie.Name,
                    Year = movie.Year,
                    Genre = movie.Genre,
                };

                return await Task.Run(() => View("View", viewModel));
            }

            return RedirectToAction("Index");
        }


        [HttpPost]
        public async Task<IActionResult> View(UpdateMovieViewModel model)
        {
            // Get The Specific Movie From The DataBase
            var movie = await movieDbContext.Movies.FindAsync(model.Id);

            if (movie != null)
            {
                movie.Name = model.Name;
                movie.Year = model.Year;
                movie.Genre = model.Genre;

                await movieDbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateMovieViewModel model)
        {
            var movie = await movieDbContext.Movies.FindAsync(model.Id);

            if (movie != null)
            {
                movieDbContext.Movies.Remove(movie);
                await movieDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }
    }
}

ScaffoldDotNet7/Views/WatchList/Add.cshtml
@model ScaffoldDotNet7.Models.AddMovieViewModel

@{
    /*inside of to form <> we will specify what form has to do After that we Push the button!*/
}
<h1>Add a Movie To Your WatchList</h1>
<form action="Add" method="post" class="mt-5">


    <div class="form-group">
        <label for="">Name</label>
        <input type="text" class="form-control" asp-for="Name">

    </div>

    <div class="form-group">
        <label for="">YearOfBuild</label>
        <input type="number" class="form-control" asp-for="Year">

    </div>

    <div class="form-group">
        <label for="">Genre</label>
        <input type="text" class="form-control" asp-for="Genre">

    </div>


    <button type="submit" class="btn btn-primary">Submit</button>
</form>

ScaffoldDotNet7/Views/WatchList/Index.cshtml
@model List<ScaffoldDotNet7.Models.Movie>



<h1>WatchLists</h1>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Year Of Build</th>
            <th>Genre</th>
            <th> </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var movie in Model)
        {
            <tr>
                <td>@movie.Id</td>
                <td>@movie.Name</td>
                <td>@movie.Year</td>
                <td>@movie.Genre</td>
                <td><a href="WatchList/View/@movie.Id">View</a></td>
            </tr>

        }
    </tbody>
</table>

ScaffoldDotNet7/Views/WatchList/View.cshtml
@model ScaffoldDotNet7.Models.UpdateMovieViewModel

<h1>Edit a Movie For Your WatchList</h1>

<form method="post" action="View" class="mt-5">

    <div class="form-group">
        <label for="">Id</label>
        <input type="text" class="form-control" asp-for="Id" readonly>

    </div>

    <div class="form-group">
        <label for="">Name</label>
        <input type="text" class="form-control" asp-for="Name">

    </div>

    <div class="form-group">
        <label for="">YearOfBuild</label>
        <input type="number" class="form-control" asp-for="Year">

    </div>

    <div class="form-group">
        <label for="">Genre</label>
        <input type="text" class="form-control" asp-for="Genre">

    </div>


    <button type="submit" class="btn btn-primary">Submit</button>

    <button type="submit" class="btn btn-danger" asp-action="Delete" asp-controller="WatchList">Delete</button>



</form>




@*<form action="View" method="post" class="mt-5">


    <div class="form-group">
        <label for="">Name</label>
        <input type="text" class="form-control" asp-for="Name">

    </div>

    <div class="form-group">
        <label for="">YearOfBuild</label>
        <input type="number" class="form-control" asp-for="Year">

    </div>

    <div class="form-group">
        <label for="">Genre</label>
        <input type="text" class="form-control" asp-for="Genre">

    </div>
*@









@*@model MovieDownloader.Models.UpdateMovieViewModel
@{
}


<h1>Update a Movie For Your WatchList</h1>
<form action="View" method="post" class="mt-5">

    <div class="form-group">
        <label for="">Id</label>
        <input type="text" class="form-control" asp-for="Id" readonly>

    </div>

    <div class="form-group">
        <label for="">Name</label>
        <input type="text" class="form-control" asp-for="Name">

    </div>

    <div class="form-group">
        <label for="">YearOfBuild</label>
        <input type="number" class="form-control" asp-for="Year">

    </div>

    <div class="form-group">
        <label for="">Genre</label>
        <input type="text" class="form-control" asp-for="Genre">

    </div>
    *@